[package]
name = "snarky-bn382"
version = "0.1.0"
authors = ["opensource@o1labs.org"]
description = "C exports for Bn382 fields"
repository = "https://github.com/o1-labs/zexe"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "snarky_bn382_stubs_stubs"
crate-type = ["staticlib"]

################################# Dependencies ################################

[dependencies]
libc = { version = "0.2.0" }
algebra = { git = "https://github.com/o1-labs/zexe/" }
ff-fft = { git = "https://github.com/o1-labs/zexe/" }
rand = { version = "0.7" }
num-bigint = { version = "0.2.3" }
sprs = { version = "0.7.1" }
rand_core = { version = "0.5" }

oracle = { git = "https://github.com/o1-labs/marlin/" }
evaluation_domains = { git = "https://github.com/o1-labs/marlin/" }

circuits_pairing = { git = "https://github.com/o1-labs/marlin/" }
commitment_pairing = { git = "https://github.com/o1-labs/marlin/" }
protocol_pairing = { git = "https://github.com/o1-labs/marlin/" }

circuits_dlog = { git = "https://github.com/o1-labs/marlin/" }
commitment_dlog = { git = "https://github.com/o1-labs/marlin/" }
protocol_dlog = { git = "https://github.com/o1-labs/marlin/" }
